// Package webui embeds the Vite-built React SPA into the QuantumAtlas
// server binary. Built artefacts live under internal/webui/dist/ and are
// regenerated by:
//
//	cd web && ./node_modules/.bin/vite build --base=/
//	cp -r web/dist/* internal/webui/dist/
//
// Then a normal `go build ./cmd/server` produces a single self-contained
// binary that serves the SPA from RAM — no external pb_public/ needed.
//
// The frontend is built with base=/ so all asset URLs are absolute root
// paths (/assets/index-*.js etc.), which keeps the static handler logic
// simple: any 404 falls back to /index.html for SPA client routing.
package webui

import (
	"embed"
	"io/fs"
)

//go:embed all:dist
var embedded embed.FS

// FS returns the embedded SPA filesystem rooted at dist/ (i.e. the
// root directory contains index.html + assets/). Returns an error
// only if the embed itself is malformed, which would be a build-time
// bug — callers are free to panic on failure.
func FS() (fs.FS, error) {
	return fs.Sub(embedded, "dist")
}

// MustFS is FS that panics on error. Suitable for main() init.
func MustFS() fs.FS {
	sub, err := FS()
	if err != nil {
		panic("webui: embedded fs unavailable: " + err.Error())
	}
	return sub
}
