"""
Code Formatter Module

Provides code formatting capabilities using black (if available).
Adds standard comment headers and ensures PEP 8 compliance.
"""

import ast
from typing import Optional, Tuple
from datetime import datetime

# Try to import black for code formatting
try:
    import black
    BLACK_AVAILABLE = True
except ImportError:
    BLACK_AVAILABLE = False


class CodeFormatter:
    """
    Formatter for generated Python code.
    
    Features:
    - Code formatting using black (if available)
    - Standard comment header generation
    - Syntax validation using AST
    - PEP 8 compliance checks
    
    Attributes:
        use_black: Whether to use black for formatting
        line_length: Maximum line length for formatting
    """
    
    def __init__(self, use_black: bool = True, line_length: int = 100):
        """
        Initialize the code formatter.
        
        Args:
            use_black: Whether to use black for formatting
            line_length: Maximum line length for code formatting
        """
        self.use_black = use_black and BLACK_AVAILABLE
        self.line_length = line_length
    
    def format(
        self,
        code: str,
        add_header: bool = True,
        validate_syntax: bool = True,
    ) -> str:
        """
        Format the given Python code.
        
        Args:
            code: Python code string to format
            add_header: Whether to add a standard header
            validate_syntax: Whether to validate syntax using AST
            
        Returns:
            Formatted code string
            
        Raises:
            SyntaxError: If code has invalid syntax and validate_syntax is True
        """
        # Validate syntax first
        if validate_syntax:
            self.validate_syntax(code)
        
        # Add header if requested
        if add_header:
            code = self._add_header(code)
        
        # Apply black formatting if available
        if self.use_black:
            code = self._apply_black(code)
        
        return code
    
    def format_file(
        self,
        filepath: str,
        add_header: bool = True,
        validate_syntax: bool = True,
    ) -> str:
        """
        Format code from a file.
        
        Args:
            filepath: Path to the Python file
            add_header: Whether to add a standard header
            validate_syntax: Whether to validate syntax using AST
            
        Returns:
            Formatted code string
        """
        with open(filepath, 'r', encoding='utf-8') as f:
            code = f.read()
        
        return self.format(code, add_header=add_header, validate_syntax=validate_syntax)
    
    def validate_syntax(self, code: str) -> bool:
        """
        Validate Python code syntax using AST.
        
        Args:
            code: Python code string to validate
            
        Returns:
            True if syntax is valid
            
        Raises:
            SyntaxError: If code has invalid syntax
        """
        try:
            ast.parse(code)
            return True
        except SyntaxError as e:
            raise SyntaxError(f"Invalid Python syntax: {e}") from e
    
    def check_syntax(self, code: str) -> Tuple[bool, Optional[str]]:
        """
        Check Python code syntax without raising exceptions.
        
        Args:
            code: Python code string to check
            
        Returns:
            Tuple of (is_valid, error_message)
        """
        try:
            ast.parse(code)
            return True, None
        except SyntaxError as e:
            return False, str(e)
    
    def _add_header(self, code: str) -> str:
        """
        Add a standard header to the code.
        
        Args:
            code: Python code string
            
        Returns:
            Code with header added
        """
        # Check if code already starts with a docstring or shebang
        stripped = code.lstrip()
        if stripped.startswith('"""') or stripped.startswith("'''") or stripped.startswith('#!'):
            return code
        
        # Check if there's already a module docstring
        lines = code.split('\n')
        first_non_empty = None
        for i, line in enumerate(lines):
            if line.strip():
                first_non_empty = i
                break
        
        if first_non_empty is not None and lines[first_non_empty].strip().startswith('"""'):
            return code
        
        # Add a simple header
        header = f'''# Generated by QuantumAtlas
# Timestamp: {datetime.now().isoformat()}

'''
        return header + code
    
    def _apply_black(self, code: str) -> str:
        """
        Apply black formatting to code.
        
        Args:
            code: Python code string
            
        Returns:
            Formatted code string
        """
        if not BLACK_AVAILABLE:
            return code
        
        try:
            # Use black's Mode for configuration
            mode = black.Mode(line_length=self.line_length)
            formatted = black.format_str(code, mode=mode)
            return formatted
        except Exception:
            # If black fails, return original code
            return code
    
    def is_black_available(self) -> bool:
        """
        Check if black is available for formatting.
        
        Returns:
            True if black is available
        """
        return BLACK_AVAILABLE
    
    @staticmethod
    def get_pep8_stats(code: str) -> dict:
        """
        Get basic PEP 8 statistics about the code.
        
        Args:
            code: Python code string
            
        Returns:
            Dictionary with statistics
        """
        lines = code.split('\n')
        stats = {
            "total_lines": len(lines),
            "blank_lines": sum(1 for line in lines if not line.strip()),
            "comment_lines": sum(1 for line in lines if line.strip().startswith('#')),
            "docstring_lines": 0,
            "max_line_length": max(len(line) for line in lines) if lines else 0,
            "lines_over_79": sum(1 for line in lines if len(line) > 79),
            "lines_over_100": sum(1 for line in lines if len(line) > 100),
        }
        
        # Count docstring lines (simple heuristic)
        in_docstring = False
        docstring_delim = None
        for line in lines:
            stripped = line.strip()
            if not in_docstring:
                if stripped.startswith('"""') or stripped.startswith("'''"):
                    in_docstring = True
                    docstring_delim = '"""' if '"""' in stripped else "'''"
                    stats["docstring_lines"] += 1
                    if stripped.count(docstring_delim) >= 2:
                        in_docstring = False
                        docstring_delim = None
            else:
                stats["docstring_lines"] += 1
                if docstring_delim in stripped:
                    in_docstring = False
                    docstring_delim = None
        
        return stats


def format_code(code: str, use_black: bool = True, line_length: int = 100) -> str:
    """
    Convenience function to format code.
    
    Args:
        code: Python code string to format
        use_black: Whether to use black for formatting
        line_length: Maximum line length
        
    Returns:
        Formatted code string
    """
    formatter = CodeFormatter(use_black=use_black, line_length=line_length)
    return formatter.format(code)


def validate_code_syntax(code: str) -> bool:
    """
    Convenience function to validate code syntax.
    
    Args:
        code: Python code string to validate
        
    Returns:
        True if syntax is valid
    """
    try:
        ast.parse(code)
        return True
    except SyntaxError:
        return False
