"""
Qiskit Code Generator

Converts QuantumCircuit to executable Qiskit Python code.
"""

from typing import Any, Dict, List, Optional
from datetime import datetime
from pathlib import Path

from ..designer.quantum_circuit import QuantumCircuit, Gate
from .template_engine import TemplateEngine, DEFAULT_TEMPLATE_DIR


class QiskitCodeGenerator:
    """
    Generator for Qiskit-compatible Python code.
    
    Converts QuantumCircuit objects to executable Qiskit Python code.
    
    Attributes:
        circuit_var_name: Variable name for the circuit in generated code
        template_engine: TemplateEngine instance for rendering
    """
    
    # Gate mapping: gate_name -> Qiskit method call pattern
    GATE_MAP = {
        "H": "{circuit}.h({qubit})",
        "X": "{circuit}.x({qubit})",
        "Y": "{circuit}.y({qubit})",
        "Z": "{circuit}.z({qubit})",
        "S": "{circuit}.s({qubit})",
        "T": "{circuit}.t({qubit})",
        "CNOT": "{circuit}.cx({control}, {target})",
        "CZ": "{circuit}.cz({control}, {target})",
        "SWAP": "{circuit}.swap({qubit1}, {qubit2})",
        "RX": "{circuit}.rx({angle}, {qubit})",
        "RY": "{circuit}.ry({angle}, {qubit})",
        "RZ": "{circuit}.rz({angle}, {qubit})",
        "MEASURE": "{circuit}.measure({qubit}, {cbit})",
    }
    
    def __init__(self, circuit_var_name: str = "circuit"):
        """
        Initialize the Qiskit code generator.
        
        Args:
            circuit_var_name: Variable name for the circuit in generated code
        """
        self.circuit_var_name = circuit_var_name
        self.template_engine = TemplateEngine()
        
        # Load default template
        template_path = DEFAULT_TEMPLATE_DIR / "qiskit_template.py.j2"
        if template_path.exists():
            self.template_engine.load_from_file(str(template_path))
            self._template_name = "qiskit_template.py.j2"
        else:
            self._template_name = None
    
    def generate(
        self,
        circuit: QuantumCircuit,
        algorithm_id: str = "quantum_circuit",
        description: str = "Quantum circuit generated by QuantumAtlas",
    ) -> str:
        """
        Generate Qiskit Python code from a QuantumCircuit.
        
        Args:
            circuit: The quantum circuit to convert
            algorithm_id: Identifier for the algorithm
            description: Description of the circuit
            
        Returns:
            Generated Python code as a string
        """
        circuit_lines = self._generate_circuit_lines(circuit)
        
        context = {
            "description": description,
            "algorithm_id": algorithm_id,
            "timestamp": datetime.now().isoformat(),
            "num_qubits": circuit.num_qubits,
            "num_clbits": circuit.num_clbits,
            "circuit_var_name": self.circuit_var_name,
            "circuit_lines": circuit_lines,
        }
        
        if self._template_name:
            return self.template_engine.render(self._template_name, **context)
        else:
            return self._generate_without_template(context)
    
    def _generate_circuit_lines(self, circuit: QuantumCircuit) -> List[str]:
        """
        Generate Qiskit code lines for circuit gates.
        
        Args:
            circuit: The quantum circuit
            
        Returns:
            List of code lines
        """
        lines = []
        
        for gate in circuit.gates:
            line = self._convert_gate(gate)
            if line:
                lines.append(line)
        
        return lines
    
    def _convert_gate(self, gate: Gate) -> Optional[str]:
        """
        Convert a gate to Qiskit code.
        
        Args:
            gate: The gate to convert
            
        Returns:
            Qiskit code string or None if gate not supported
        """
        if gate.name not in self.GATE_MAP:
            return f"# Unsupported gate: {gate.name}"
        
        template = self.GATE_MAP[gate.name]
        
        if gate.name == "MEASURE":
            return template.format(
                circuit=self.circuit_var_name,
                qubit=gate.target_qubits[0],
                cbit=gate.classical_bits[0],
            )
        
        elif gate.name in ["CNOT", "CZ"]:
            return template.format(
                circuit=self.circuit_var_name,
                control=gate.control_qubits[0],
                target=gate.target_qubits[0],
            )
        
        elif gate.name == "SWAP":
            return template.format(
                circuit=self.circuit_var_name,
                qubit1=gate.target_qubits[0],
                qubit2=gate.target_qubits[1],
            )
        
        elif gate.name in ["RX", "RY", "RZ"]:
            angle = gate.params.get("theta", 0.0)
            return template.format(
                circuit=self.circuit_var_name,
                qubit=gate.target_qubits[0],
                angle=angle,
            )
        
        else:
            # Single qubit gates
            return template.format(
                circuit=self.circuit_var_name,
                qubit=gate.target_qubits[0],
            )
    
    def _generate_without_template(self, context: Dict[str, Any]) -> str:
        """
        Generate code without using a template (fallback).
        
        Args:
            context: Template context
            
        Returns:
            Generated Python code
        """
        lines = [
            f'"""',
            f"{context['description']}",
            f"",
            f"Auto-generated by QuantumAtlas Code Generator",
            f"Backend: Qiskit",
            f"Algorithm: {context['algorithm_id']}",
            f'"""',
            f"",
            f"from qiskit import QuantumCircuit, ClassicalRegister, QuantumRegister",
            f"",
            f"def create_circuit():",
            f'    """Create the quantum circuit."""',
            f"    qr = QuantumRegister({context['num_qubits']}, name='q')",
            f"    cr = ClassicalRegister({context['num_clbits']}, name='c')",
            f"    circuit = QuantumCircuit(qr, cr, name='{context['algorithm_id']}')",
        ]
        
        for line in context['circuit_lines']:
            lines.append(f"    {line}")
        
        lines.extend([
            f"    return circuit",
            f"",
            f'if __name__ == "__main__":',
            f"    circuit = create_circuit()",
            f"    print(circuit.draw())",
        ])
        
        return "\n".join(lines)
    
    def get_supported_gates(self) -> List[str]:
        """
        Get list of supported gate names.
        
        Returns:
            List of supported gate names
        """
        return list(self.GATE_MAP.keys())
