"""Tests for CodeFormatter."""

import ast
from pathlib import Path

import pytest

from qatlas.codegen.formatter import CodeFormatter, format_code, validate_code_syntax


class TestCodeFormatter:
    """Test cases for CodeFormatter."""
    
    def test_formatter_initialization(self):
        """Test formatter initialization."""
        formatter = CodeFormatter(use_black=True)
        assert formatter.use_black == (formatter.is_black_available())
        
        formatter = CodeFormatter(use_black=False)
        assert formatter.use_black is False
    
    def test_format_valid_code(self):
        """Test formatting valid Python code."""
        formatter = CodeFormatter(use_black=False)
        
        code = """
x=1+2
y   =   3
"""
        result = formatter.format(code, add_header=False)
        
        # Result should be a string
        assert isinstance(result, str)
        assert "x = 1 + 2" in result or "x=1+2" in result
    
    def test_format_invalid_code(self):
        """Test formatting invalid Python code raises error."""
        formatter = CodeFormatter(use_black=False)
        
        code = "def broken_syntax("
        with pytest.raises(SyntaxError):
            formatter.format(code)
    
    def test_validate_syntax_valid(self):
        """Test validating valid Python syntax."""
        formatter = CodeFormatter(use_black=False)
        
        code = """
def hello():
    return "world"

x = 1 + 2
"""
        is_valid = formatter.validate_syntax(code)
        assert is_valid is True
    
    def test_validate_syntax_invalid(self):
        """Test validating invalid Python syntax raises error."""
        formatter = CodeFormatter(use_black=False)
        
        code = "def broken("
        with pytest.raises(SyntaxError):
            formatter.validate_syntax(code)
    
    def test_check_syntax_valid(self):
        """Test check_syntax with valid code."""
        formatter = CodeFormatter(use_black=False)
        
        code = "x = 1 + 2"
        is_valid, error = formatter.check_syntax(code)
        assert is_valid is True
        assert error is None
    
    def test_check_syntax_invalid(self):
        """Test check_syntax with invalid code."""
        formatter = CodeFormatter(use_black=False)
        
        code = "def broken("
        is_valid, error = formatter.check_syntax(code)
        assert is_valid is False
        assert error is not None
    
    def test_add_header(self):
        """Test adding header to code."""
        formatter = CodeFormatter(use_black=False)
        
        code = "x = 1"
        result = formatter.format(code, add_header=True)
        
        # Should contain header
        assert "Generated by QuantumAtlas" in result
    
    def test_format_without_header(self):
        """Test formatting without adding header."""
        formatter = CodeFormatter(use_black=False)
        
        code = "x = 1"
        result = formatter.format(code, add_header=False)
        
        # Should not add header
        assert "Generated by QuantumAtlas" not in result
    
    def test_format_empty_code(self):
        """Test formatting empty code."""
        formatter = CodeFormatter(use_black=False)
        
        result = formatter.format("", add_header=False)
        
        assert isinstance(result, str)
    
    def test_format_whitespace_only(self):
        """Test formatting whitespace-only code."""
        formatter = CodeFormatter(use_black=False)
        
        result = formatter.format("   \n\t  \n  ", add_header=False)
        
        assert isinstance(result, str)
    
    def test_complex_code_formatting(self):
        """Test formatting complex quantum circuit code."""
        formatter = CodeFormatter(use_black=False)
        
        code = '''
from pyqpanda import *

def create_circuit():
    qvm=CPUQVM()
    qvm.init_qvm()
    qubits=qvm.qAlloc_many(2)
    cbits=qvm.cAlloc_many(2)
    prog=QProg()
    prog.insert(H(qubits[0]))
    prog.insert(CNOT(qubits[0],qubits[1]))
    return prog,qubits,cbits
'''
        result = formatter.format(code, add_header=False)
        
        # Check that code is valid Python
        try:
            ast.parse(result)
        except SyntaxError:
            pytest.fail("Formatted code has syntax errors")
    
    def test_format_preserves_comments(self):
        """Test that formatting preserves comments."""
        formatter = CodeFormatter(use_black=False)
        
        code = '''
# This is a comment
x = 1  # inline comment
# Another comment
y = 2
'''
        result = formatter.format(code, add_header=False)
        
        # Comments should be preserved (though formatting may vary)
        assert "comment" in result.lower()
    
    def test_format_file(self, tmp_path):
        """Test formatting code from file."""
        formatter = CodeFormatter(use_black=False)
        
        # Create a test file
        test_file = tmp_path / "test_code.py"
        test_file.write_text("x = 1 + 2\n")
        
        result = formatter.format_file(str(test_file), add_header=False)
        
        assert isinstance(result, str)
        assert "x = 1 + 2" in result
    
    def test_get_pep8_stats(self):
        """Test getting PEP 8 statistics."""
        formatter = CodeFormatter(use_black=False)
        
        code = """
# Comment line
x = 1

y = 2
"""
        stats = formatter.get_pep8_stats(code)
        
        assert "total_lines" in stats
        assert "blank_lines" in stats
        assert "comment_lines" in stats
        assert stats["total_lines"] > 0
    
    def test_is_black_available(self):
        """Test checking if black is available."""
        formatter = CodeFormatter()
        
        # Should return a boolean
        result = formatter.is_black_available()
        assert isinstance(result, bool)
    
    def test_line_length_configuration(self):
        """Test line length configuration."""
        formatter = CodeFormatter(use_black=False, line_length=80)
        assert formatter.line_length == 80
        
        formatter = CodeFormatter(use_black=False, line_length=120)
        assert formatter.line_length == 120


class TestCodeFormatterIntegration:
    """Integration tests for CodeFormatter."""
    
    def test_full_formatting_pipeline(self):
        """Test complete formatting pipeline."""
        formatter = CodeFormatter(use_black=False)
        
        raw_code = """
def test_func( ):
    x=1+2
    y    =   3
    return x+y
"""
        
        result = formatter.format(raw_code, add_header=True)
        
        assert isinstance(result, str)
        assert "Generated by QuantumAtlas" in result
        
        # Verify it's valid Python
        assert formatter.validate_syntax(result)


class TestConvenienceFunctions:
    """Test convenience functions."""
    
    def test_format_code_function(self):
        """Test format_code convenience function."""
        code = "x=1+2"
        result = format_code(code, use_black=False)
        
        assert isinstance(result, str)
    
    def test_validate_code_syntax_function_valid(self):
        """Test validate_code_syntax with valid code."""
        code = "x = 1 + 2"
        result = validate_code_syntax(code)
        
        assert result is True
    
    def test_validate_code_syntax_function_invalid(self):
        """Test validate_code_syntax with invalid code."""
        code = "def broken("
        result = validate_code_syntax(code)
        
        assert result is False


if __name__ == "__main__":
    pytest.main([__file__, "-v"])
