"""YAML config schema for the ``qatlas`` user-level CLI.

Bridges the new ``~/.config/qatlas/config.yaml`` format introduced in
v0.16.0 to the existing env-var-driven plumbing (``ServerConfig``,
``resolve_token``, ``get_wiki_root``, ...). The YAML schema is a
deliberately simple two-level dict; every leaf maps 1:1 to an existing
env-var name via :data:`YAML_TO_ENV` so the rest of the codebase keeps
reading ``os.environ`` without per-field knowledge of where the value
ultimately came from.

This file is the SINGLE SOURCE OF TRUTH for the YAML schema. Any
field you want to expose to ``qatlas config init/set/get/show`` MUST
appear in :data:`YAML_TO_ENV`. Adding a key only to ``ServerConfig``
won't make it surface here; that's intentional — we limit the YAML
surface to fields a normal user might touch, and force a deliberate
decision (with a code review) before something new gets a YAML home.

Design choices and the rationale we pushed back on:

* **Hand-written flat map** instead of ``server.url`` → naive
  ``QATLAS_SERVER_URL`` rule. The historical env names don't share a
  prefix scheme (it's ``QATLAS_SERVER_URL`` not ``QATLAS_SERVER_URL``
  — wait, that one matches — but it's ``QATLAS_TOKEN`` not
  ``QATLAS_SERVER_TOKEN``, and ``QATLAS_WIKI_DIR`` not
  ``QATLAS_WIKI_DIR``). Any rule we'd invent would have exceptions; a
  hand map is explicit, greppable, and the wrong value can't sneak
  into ``os.environ`` because we'd fail a unit test.

* **PyYAML, no ruamel.yaml.** ``qatlas config set FOO=bar`` will
  rewrite the file and PyYAML drops user-written comments on the
  round-trip. We accept that (matches gh / kubectl behaviour) and
  warn about it in the header comment generated by ``config init``.

* **`os.environ.setdefault`** (not assignment) so an env var the user
  set in the shell always wins over what config.yaml says. Matches the
  ``godotenv`` non-override semantic the Go server uses for symmetry.
"""

from __future__ import annotations

import logging
import os
from pathlib import Path
from typing import Any, Dict, Iterable, List, Optional, Tuple

logger = logging.getLogger(__name__)


# (yaml_path, env_var_name)
# yaml_path is a tuple of nested keys, e.g. ("server", "url") for
# {"server": {"url": "..."}}. env_var_name is the canonical name we
# inject into os.environ.
#
# When adding a new entry: keep entries grouped by top-level section
# (server, wiki, mineru, extractor) and within a group ordered by
# how prominent the field is. The order here also drives the order
# config.yaml is generated in by `qatlas config init`.
YAML_TO_ENV: Dict[Tuple[str, ...], str] = {
    # Server endpoint + auth — the only fields most users will ever set.
    ("server", "url"):            "QATLAS_SERVER_URL",
    ("server", "token"):          "QATLAS_TOKEN",
    ("server", "insecure"):       "QATLAS_INSECURE",

    # Local wiki repo — only needed for `qatlas wiki list/show/lint/search`.
    ("wiki", "dir"):              "QATLAS_WIKI_DIR",

    # MinerU (third-party PDF→Markdown). Only relevant to contributors
    # who run `qatlas mineru` to produce local markdown for upload.
    # NB: top-level alias = the third-party-conventional MINERU_*, not
    # QATLAS_MINERU_*, because MinerU's official SDK reads those env names.
    ("mineru", "api_token"):      "MINERU_API_TOKEN",
    ("mineru", "api_base_url"):   "MINERU_API_BASE_URL",
    ("mineru", "model_version"):  "MINERU_MODEL_VERSION",
    ("mineru", "language"):       "MINERU_LANGUAGE",
    ("mineru", "is_ocr"):         "MINERU_IS_OCR",
    ("mineru", "enable_formula"): "MINERU_ENABLE_FORMULA",
    ("mineru", "enable_table"):   "MINERU_ENABLE_TABLE",
    ("mineru", "poll_interval"):  "MINERU_POLL_INTERVAL",
    ("mineru", "timeout"):        "MINERU_TIMEOUT",

    # `qatlas extractor` (experimental LLM extraction). OpenAI /
    # Anthropic env names are SDK-conventional too — kept as-is.
    ("extractor", "openai_api_key"):    "OPENAI_API_KEY",
    ("extractor", "anthropic_api_key"): "ANTHROPIC_API_KEY",
}


# Reverse map for converting a dict of env_name → value back into a
# nested YAML dict (used by the .env → config.yaml auto-migration).
# Built once at import time. Env names not in this map are NOT
# migrated — they stay in the legacy .env file (or get dropped if the
# user moves on).
ENV_TO_YAML: Dict[str, Tuple[str, ...]] = {env: path for path, env in YAML_TO_ENV.items()}


# Fields that are best presented to the user as boolean YAML literals
# (true/false) rather than the string "1"/"0" or "true"/"false" we'd
# inject into os.environ. The actual env value remains a string —
# downstream consumers (pydantic field_validator) already coerce
# strings — but the YAML representation is nicer.
_BOOL_YAML_PATHS = {
    ("server", "insecure"),
    ("mineru", "is_ocr"),
    ("mineru", "enable_formula"),
    ("mineru", "enable_table"),
}

# Same idea for numeric fields.
_NUMERIC_YAML_PATHS = {
    ("mineru", "poll_interval"),  # float
    ("mineru", "timeout"),        # int
}


HEADER_COMMENT = """\
# QuantumAtlas client config
#
# Managed by `qatlas config init/set/unset` — those commands will REWRITE
# this file and drop any hand-written comments (matches the gh / kubectl
# `config set` behaviour). If you want persistent notes, keep them in a
# wrapper script that exports QATLAS_* / MINERU_* env vars instead.
#
# Resolution order (see `qatlas config path`):
#   1. CLI flag (--server-url / --token / --insecure / ...)
#   2. OS env var (QATLAS_*, MINERU_*, OPENAI_*, ANTHROPIC_*)
#   3. $QATLAS_CONFIG (explicit YAML override)
#   4. $QATLAS_DOTENV (legacy .env override; ⚠️ deprecated, removed in v0.17.0)
#   5. ~/.config/qatlas/config.yaml          ← this file
#   6. ~/.config/qatlas/.env                 ← legacy, will auto-migrate
#   7. Built-in defaults defined in qatlas/config.py
"""


def load_yaml_file(path: Path) -> Dict[str, Any]:
    """Read a YAML file and return its top-level dict (empty when empty
    file or missing). Raises ``ValueError`` on parse error so callers
    can surface a clear message instead of opaque YAML tracebacks.
    """
    if not path.is_file():
        return {}
    import yaml  # localised import so the module imports cleanly even when pyyaml is unavailable
    try:
        loaded = yaml.safe_load(path.read_text(encoding="utf-8"))
    except yaml.YAMLError as exc:
        raise ValueError(f"failed to parse {path}: {exc}") from exc
    if loaded is None:
        return {}
    if not isinstance(loaded, dict):
        raise ValueError(
            f"{path}: expected a top-level mapping (key: value structure), "
            f"got {type(loaded).__name__}"
        )
    return loaded


def flatten_yaml_to_env(data: Dict[str, Any]) -> Dict[str, str]:
    """Walk a YAML dict and produce a ``{env_name: stringified_value}``
    dict using :data:`YAML_TO_ENV`.

    * Keys not in YAML_TO_ENV are silently ignored with a debug log,
      not raised, so adding a future-proof "extras" section to the file
      doesn't break older qatlas versions.
    * ``None`` and empty-string values are dropped (same semantic as
      "field absent").
    * Booleans are lowercased ("True" → "true") because downstream
      ``field_validator._parse_true_only_bool`` matches the literal
      string ``"true"`` only.
    * Other types are ``str()``-ed.
    """
    out: Dict[str, str] = {}
    for path, env_name in YAML_TO_ENV.items():
        value = _walk(data, path)
        if value is None:
            continue
        if isinstance(value, bool):
            out[env_name] = "true" if value else "false"
        elif isinstance(value, str):
            if value == "":
                continue
            out[env_name] = value
        else:
            out[env_name] = str(value)
    # Detect / log unknown sections so users get told when they typo'd
    # `server.urll` etc. — invaluable for debugging "why isn't my
    # config being picked up?".
    for path in _all_leaf_paths(data):
        if path not in YAML_TO_ENV:
            logger.debug("config.yaml: unknown key %s (ignored)", ".".join(path))
    return out


def env_dict_to_yaml(env_pairs: Dict[str, str]) -> Dict[str, Any]:
    """Convert a dict of env_name → value back into a nested YAML
    structure. Used by the .env → config.yaml auto-migration.

    Env vars not in :data:`ENV_TO_YAML` are dropped — by design,
    migration is lossy on purpose (legacy QATLAS_POCKETBASE_URL etc.
    don't belong in client config). The dropped names are returned
    via ``unmigrated_keys()`` so callers can inform the user.
    """
    out: Dict[str, Any] = {}
    for env_name, raw in env_pairs.items():
        if raw == "" or raw is None:
            continue
        path = ENV_TO_YAML.get(env_name)
        if path is None:
            continue
        value: Any = raw
        if path in _BOOL_YAML_PATHS:
            value = raw.strip().lower() in {"1", "true", "yes", "on"}
        elif path in _NUMERIC_YAML_PATHS:
            try:
                if path == ("mineru", "poll_interval"):
                    value = float(raw)
                else:
                    value = int(raw)
            except (TypeError, ValueError):
                # Keep the raw string so the user can fix it manually
                # instead of silently losing the value.
                value = raw
        _set_nested(out, path, value)
    return out


def unmigrated_keys(env_pairs: Dict[str, str]) -> List[str]:
    """List env_name keys present in ``env_pairs`` that have NO YAML
    schema home and would therefore be dropped by
    :func:`env_dict_to_yaml`. Returned in input order.
    """
    return [k for k, v in env_pairs.items() if v and k not in ENV_TO_YAML]


def dump_yaml(data: Dict[str, Any]) -> str:
    """Serialise a YAML dict back to text with the header comment.

    ``sort_keys=False`` so the section order in YAML_TO_ENV is
    preserved (PyYAML otherwise alphabetises, which buries the
    user-relevant ``server`` section beneath ``extractor`` /
    ``mineru``).
    """
    import yaml  # localised import; see load_yaml_file()
    body = yaml.safe_dump(data, sort_keys=False, allow_unicode=True, default_flow_style=False)
    return HEADER_COMMENT + "\n" + body


def bootstrap_env_from_yaml(path: Path) -> None:
    """Read ``path`` (config.yaml), flatten to env vars, and inject
    into ``os.environ`` with ``setdefault`` semantics.

    Matches :func:`qatlas.config.bootstrap_env` for the legacy .env
    path — a real env var ALWAYS wins over the file. No-op when the
    file doesn't exist (resolution decisions happen one level up).
    """
    pairs = flatten_yaml_to_env(load_yaml_file(path))
    for env_name, value in pairs.items():
        os.environ.setdefault(env_name, value)


# ---------------------------------------------------------------------------
# tiny dict utilities — kept private to avoid polluting the module surface
# ---------------------------------------------------------------------------


def _walk(data: Dict[str, Any], path: Tuple[str, ...]) -> Any:
    cur: Any = data
    for key in path:
        if not isinstance(cur, dict):
            return None
        cur = cur.get(key)
        if cur is None:
            return None
    return cur


def _set_nested(out: Dict[str, Any], path: Tuple[str, ...], value: Any) -> None:
    cur: Dict[str, Any] = out
    for key in path[:-1]:
        nxt = cur.get(key)
        if not isinstance(nxt, dict):
            nxt = {}
            cur[key] = nxt
        cur = nxt
    cur[path[-1]] = value


def _all_leaf_paths(data: Any, prefix: Tuple[str, ...] = ()) -> Iterable[Tuple[str, ...]]:
    if isinstance(data, dict):
        for k, v in data.items():
            yield from _all_leaf_paths(v, prefix + (str(k),))
    else:
        yield prefix


# ---------------------------------------------------------------------------
# `qatlas config set/get/unset` plumbing — operate on the YAML by env-var name
# ---------------------------------------------------------------------------


def yaml_path_for_env(env_name: str) -> Optional[Tuple[str, ...]]:
    """Return the YAML key path for a given env var name, or None if
    the env var has no YAML home (i.e. set/unset would be a no-op).
    """
    return ENV_TO_YAML.get(env_name)


def set_yaml_value(data: Dict[str, Any], env_name: str, raw_value: str) -> bool:
    """Apply ``KEY=raw_value`` to a loaded yaml dict in place.

    Returns True when the key was applied (i.e. it has a YAML home),
    False when the env name is unknown (caller should error out).
    Boolean / numeric coercion follows the same rules as
    :func:`env_dict_to_yaml`.
    """
    path = yaml_path_for_env(env_name)
    if path is None:
        return False
    value: Any = raw_value
    if path in _BOOL_YAML_PATHS:
        value = raw_value.strip().lower() in {"1", "true", "yes", "on"}
    elif path in _NUMERIC_YAML_PATHS:
        try:
            if path == ("mineru", "poll_interval"):
                value = float(raw_value)
            else:
                value = int(raw_value)
        except (TypeError, ValueError):
            value = raw_value
    _set_nested(data, path, value)
    return True


def unset_yaml_value(data: Dict[str, Any], env_name: str) -> bool:
    """Delete a key by env-var name from a loaded yaml dict. Returns
    True when something was removed, False otherwise. Also prunes
    now-empty parent sections so the file doesn't accrue ``mineru:
    {}`` shells.
    """
    path = yaml_path_for_env(env_name)
    if path is None:
        return False
    if not _delete_nested(data, path):
        return False
    # Trim empty parent dicts.
    parents: List[Tuple[Dict[str, Any], str]] = []
    cur: Dict[str, Any] = data
    for key in path[:-1]:
        nxt = cur.get(key)
        if not isinstance(nxt, dict):
            break
        parents.append((cur, key))
        cur = nxt
    for parent, key in reversed(parents):
        if isinstance(parent.get(key), dict) and not parent[key]:
            del parent[key]
    return True


def _delete_nested(data: Dict[str, Any], path: Tuple[str, ...]) -> bool:
    cur: Any = data
    for key in path[:-1]:
        if not isinstance(cur, dict) or key not in cur:
            return False
        cur = cur[key]
    if isinstance(cur, dict) and path[-1] in cur:
        del cur[path[-1]]
        return True
    return False


def get_yaml_value(data: Dict[str, Any], env_name: str) -> Optional[str]:
    """Look up a value from a loaded yaml dict by env-var name. Returns
    None when absent. Booleans are rendered as ``"true"`` / ``"false"``.
    """
    path = yaml_path_for_env(env_name)
    if path is None:
        return None
    value = _walk(data, path)
    if value is None:
        return None
    if isinstance(value, bool):
        return "true" if value else "false"
    return str(value)
