"""
QPanda Code Generator

Converts QuantumCircuit to executable QPanda Python code.
"""

from typing import Any, Dict, List, Optional
from datetime import datetime
from pathlib import Path

from ..designer.quantum_circuit import QuantumCircuit, Gate
from .template_engine import TemplateEngine, DEFAULT_TEMPLATE_DIR


class QPandaCodeGenerator:
    """
    Generator for QPanda-compatible Python code.
    
    Converts QuantumCircuit objects to executable QPanda Python code.
    
    Attributes:
        circuit_var_name: Variable name for the circuit in generated code
        template_engine: TemplateEngine instance for rendering
    """
    
    # Gate mapping: gate_name -> QPanda method call pattern
    GATE_MAP = {
        "H": "{circuit}.H(qubits[{qubit}])",
        "X": "{circuit}.X(qubits[{qubit}])",
        "Y": "{circuit}.Y(qubits[{qubit}])",
        "Z": "{circuit}.Z(qubits[{qubit}])",
        "S": "{circuit}.S(qubits[{qubit}])",
        "T": "{circuit}.T(qubits[{qubit}])",
        "CNOT": "{circuit}.CNOT(qubits[{control}], qubits[{target}])",
        "CZ": "{circuit}.CZ(qubits[{control}], qubits[{target}])",
        "SWAP": "{circuit}.SWAP(qubits[{qubit1}], qubits[{qubit2}])",
        "RX": "{circuit}.RX(qubits[{qubit}], {angle})",
        "RY": "{circuit}.RY(qubits[{qubit}], {angle})",
        "RZ": "{circuit}.RZ(qubits[{qubit}], {angle})",
        "MEASURE": "# Measurement added separately",  # Handled separately
    }
    
    def __init__(self, circuit_var_name: str = "circuit"):
        """
        Initialize the QPanda code generator.
        
        Args:
            circuit_var_name: Variable name for the circuit in generated code
        """
        self.circuit_var_name = circuit_var_name
        self.template_engine = TemplateEngine()
        
        # Load default template
        template_path = DEFAULT_TEMPLATE_DIR / "qpanda_template.py.j2"
        if template_path.exists():
            self.template_engine.load_from_file(str(template_path))
            self._template_name = "qpanda_template.py.j2"
        else:
            self._template_name = None
    
    def generate(
        self,
        circuit: QuantumCircuit,
        algorithm_id: str = "quantum_circuit",
        description: str = "Quantum circuit generated by QuantumAtlas",
    ) -> str:
        """
        Generate QPanda Python code from a QuantumCircuit.
        
        Args:
            circuit: The quantum circuit to convert
            algorithm_id: Identifier for the algorithm
            description: Description of the circuit
            
        Returns:
            Generated Python code as a string
        """
        circuit_lines = self._generate_circuit_lines(circuit)
        
        context = {
            "description": description,
            "algorithm_id": algorithm_id,
            "timestamp": datetime.now().isoformat(),
            "num_qubits": circuit.num_qubits,
            "num_clbits": circuit.num_clbits,
            "circuit_var_name": self.circuit_var_name,
            "circuit_lines": circuit_lines,
            "has_measurement": any(g.name == "MEASURE" for g in circuit.gates),
        }
        
        if self._template_name:
            return self.template_engine.render(self._template_name, **context)
        else:
            return self._generate_without_template(context)
    
    def _generate_circuit_lines(self, circuit: QuantumCircuit) -> List[str]:
        """
        Generate QPanda code lines for circuit gates.
        
        Args:
            circuit: The quantum circuit
            
        Returns:
            List of code lines
        """
        lines = []
        
        for gate in circuit.gates:
            line = self._convert_gate(gate)
            if line:
                lines.append(line)
        
        return lines
    
    def _convert_gate(self, gate: Gate) -> Optional[str]:
        """
        Convert a gate to QPanda code.
        
        Args:
            gate: The gate to convert
            
        Returns:
            QPanda code string or None if gate not supported
        """
        if gate.name not in self.GATE_MAP:
            return f"    # Unsupported gate: {gate.name}"
        
        template = self.GATE_MAP[gate.name]
        
        if gate.name == "MEASURE":
            # Measurement is handled separately in the template
            return None
        
        elif gate.name in ["CNOT", "CZ"]:
            return template.format(
                circuit=self.circuit_var_name,
                control=gate.control_qubits[0],
                target=gate.target_qubits[0],
            )
        
        elif gate.name == "SWAP":
            return template.format(
                circuit=self.circuit_var_name,
                qubit1=gate.target_qubits[0],
                qubit2=gate.target_qubits[1],
            )
        
        elif gate.name in ["RX", "RY", "RZ"]:
            angle = gate.params.get("theta", 0.0)
            return template.format(
                circuit=self.circuit_var_name,
                qubit=gate.target_qubits[0],
                angle=angle,
            )
        
        else:
            # Single qubit gates
            return template.format(
                circuit=self.circuit_var_name,
                qubit=gate.target_qubits[0],
            )
    
    def _generate_without_template(self, context: Dict[str, Any]) -> str:
        """
        Generate code without using a template (fallback).
        
        Args:
            context: Template context
            
        Returns:
            Generated Python code
        """
        lines = [
            f'"""',
            f"{context['description']}",
            f"",
            f"Auto-generated by QuantumAtlas Code Generator",
            f"Backend: QPanda",
            f"Algorithm: {context['algorithm_id']}",
            f'"""',
            f"",
            f"from pyqpanda import *",
            f"import numpy as np",
            f"",
            f"def create_circuit():",
            f'    """Create the quantum circuit."""',
            f"    qvm = CPUQVM()",
            f"    qvm.init_qvm()",
            f"    qubits = qvm.qAlloc_many({context['num_qubits']})",
            f"    cbits = qvm.cAlloc_many({context['num_clbits']})",
            f"    circuit = QCircuit()",
        ]
        
        for line in context['circuit_lines']:
            lines.append(f"    {line}")
        
        lines.extend([
            f"    return qvm, circuit, qubits, cbits",
            f"",
            f'if __name__ == "__main__":',
            f"    qvm, circuit, qubits, cbits = create_circuit()",
        ])
        
        return "\n".join(lines)
    
    def get_supported_gates(self) -> List[str]:
        """
        Get list of supported gate names.
        
        Returns:
            List of supported gate names
        """
        return list(self.GATE_MAP.keys())
