/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PatRouteImport } from './routes/pat'
import { Route as LoginRouteImport } from './routes/login'
import { Route as LangRouteImport } from './routes/$lang'
import { Route as IndexRouteImport } from './routes/index'
import { Route as LangIndexRouteImport } from './routes/$lang.index'
import { Route as AuthCallbackRouteImport } from './routes/auth.callback'
import { Route as LangPatRouteImport } from './routes/$lang.pat'
import { Route as LangWikiIndexRouteImport } from './routes/$lang.wiki.index'
import { Route as LangGraphIndexRouteImport } from './routes/$lang.graph.index'
import { Route as LangWikiSearchRouteImport } from './routes/$lang.wiki.search'
import { Route as LangWikiPageSplatRouteImport } from './routes/$lang.wiki.page.$'
import { Route as LangGraphNodeSplatRouteImport } from './routes/$lang.graph.node.$'

const PatRoute = PatRouteImport.update({
  id: '/pat',
  path: '/pat',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const LangRoute = LangRouteImport.update({
  id: '/$lang',
  path: '/$lang',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const LangIndexRoute = LangIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LangRoute,
} as any)
const AuthCallbackRoute = AuthCallbackRouteImport.update({
  id: '/auth/callback',
  path: '/auth/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const LangPatRoute = LangPatRouteImport.update({
  id: '/pat',
  path: '/pat',
  getParentRoute: () => LangRoute,
} as any)
const LangWikiIndexRoute = LangWikiIndexRouteImport.update({
  id: '/wiki/',
  path: '/wiki/',
  getParentRoute: () => LangRoute,
} as any)
const LangGraphIndexRoute = LangGraphIndexRouteImport.update({
  id: '/graph/',
  path: '/graph/',
  getParentRoute: () => LangRoute,
} as any)
const LangWikiSearchRoute = LangWikiSearchRouteImport.update({
  id: '/wiki/search',
  path: '/wiki/search',
  getParentRoute: () => LangRoute,
} as any)
const LangWikiPageSplatRoute = LangWikiPageSplatRouteImport.update({
  id: '/wiki/page/$',
  path: '/wiki/page/$',
  getParentRoute: () => LangRoute,
} as any)
const LangGraphNodeSplatRoute = LangGraphNodeSplatRouteImport.update({
  id: '/graph/node/$',
  path: '/graph/node/$',
  getParentRoute: () => LangRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$lang': typeof LangRouteWithChildren
  '/login': typeof LoginRoute
  '/pat': typeof PatRoute
  '/$lang/pat': typeof LangPatRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/$lang/': typeof LangIndexRoute
  '/$lang/wiki/search': typeof LangWikiSearchRoute
  '/$lang/graph/': typeof LangGraphIndexRoute
  '/$lang/wiki/': typeof LangWikiIndexRoute
  '/$lang/graph/node/$': typeof LangGraphNodeSplatRoute
  '/$lang/wiki/page/$': typeof LangWikiPageSplatRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/pat': typeof PatRoute
  '/$lang/pat': typeof LangPatRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/$lang': typeof LangIndexRoute
  '/$lang/wiki/search': typeof LangWikiSearchRoute
  '/$lang/graph': typeof LangGraphIndexRoute
  '/$lang/wiki': typeof LangWikiIndexRoute
  '/$lang/graph/node/$': typeof LangGraphNodeSplatRoute
  '/$lang/wiki/page/$': typeof LangWikiPageSplatRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/$lang': typeof LangRouteWithChildren
  '/login': typeof LoginRoute
  '/pat': typeof PatRoute
  '/$lang/pat': typeof LangPatRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/$lang/': typeof LangIndexRoute
  '/$lang/wiki/search': typeof LangWikiSearchRoute
  '/$lang/graph/': typeof LangGraphIndexRoute
  '/$lang/wiki/': typeof LangWikiIndexRoute
  '/$lang/graph/node/$': typeof LangGraphNodeSplatRoute
  '/$lang/wiki/page/$': typeof LangWikiPageSplatRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$lang'
    | '/login'
    | '/pat'
    | '/$lang/pat'
    | '/auth/callback'
    | '/$lang/'
    | '/$lang/wiki/search'
    | '/$lang/graph/'
    | '/$lang/wiki/'
    | '/$lang/graph/node/$'
    | '/$lang/wiki/page/$'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/pat'
    | '/$lang/pat'
    | '/auth/callback'
    | '/$lang'
    | '/$lang/wiki/search'
    | '/$lang/graph'
    | '/$lang/wiki'
    | '/$lang/graph/node/$'
    | '/$lang/wiki/page/$'
  id:
    | '__root__'
    | '/'
    | '/$lang'
    | '/login'
    | '/pat'
    | '/$lang/pat'
    | '/auth/callback'
    | '/$lang/'
    | '/$lang/wiki/search'
    | '/$lang/graph/'
    | '/$lang/wiki/'
    | '/$lang/graph/node/$'
    | '/$lang/wiki/page/$'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LangRoute: typeof LangRouteWithChildren
  LoginRoute: typeof LoginRoute
  PatRoute: typeof PatRoute
  AuthCallbackRoute: typeof AuthCallbackRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/pat': {
      id: '/pat'
      path: '/pat'
      fullPath: '/pat'
      preLoaderRoute: typeof PatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$lang': {
      id: '/$lang'
      path: '/$lang'
      fullPath: '/$lang'
      preLoaderRoute: typeof LangRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$lang/': {
      id: '/$lang/'
      path: '/'
      fullPath: '/$lang/'
      preLoaderRoute: typeof LangIndexRouteImport
      parentRoute: typeof LangRoute
    }
    '/auth/callback': {
      id: '/auth/callback'
      path: '/auth/callback'
      fullPath: '/auth/callback'
      preLoaderRoute: typeof AuthCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$lang/pat': {
      id: '/$lang/pat'
      path: '/pat'
      fullPath: '/$lang/pat'
      preLoaderRoute: typeof LangPatRouteImport
      parentRoute: typeof LangRoute
    }
    '/$lang/wiki/': {
      id: '/$lang/wiki/'
      path: '/wiki'
      fullPath: '/$lang/wiki/'
      preLoaderRoute: typeof LangWikiIndexRouteImport
      parentRoute: typeof LangRoute
    }
    '/$lang/graph/': {
      id: '/$lang/graph/'
      path: '/graph'
      fullPath: '/$lang/graph/'
      preLoaderRoute: typeof LangGraphIndexRouteImport
      parentRoute: typeof LangRoute
    }
    '/$lang/wiki/search': {
      id: '/$lang/wiki/search'
      path: '/wiki/search'
      fullPath: '/$lang/wiki/search'
      preLoaderRoute: typeof LangWikiSearchRouteImport
      parentRoute: typeof LangRoute
    }
    '/$lang/wiki/page/$': {
      id: '/$lang/wiki/page/$'
      path: '/wiki/page/$'
      fullPath: '/$lang/wiki/page/$'
      preLoaderRoute: typeof LangWikiPageSplatRouteImport
      parentRoute: typeof LangRoute
    }
    '/$lang/graph/node/$': {
      id: '/$lang/graph/node/$'
      path: '/graph/node/$'
      fullPath: '/$lang/graph/node/$'
      preLoaderRoute: typeof LangGraphNodeSplatRouteImport
      parentRoute: typeof LangRoute
    }
  }
}

interface LangRouteChildren {
  LangPatRoute: typeof LangPatRoute
  LangIndexRoute: typeof LangIndexRoute
  LangWikiSearchRoute: typeof LangWikiSearchRoute
  LangGraphIndexRoute: typeof LangGraphIndexRoute
  LangWikiIndexRoute: typeof LangWikiIndexRoute
  LangGraphNodeSplatRoute: typeof LangGraphNodeSplatRoute
  LangWikiPageSplatRoute: typeof LangWikiPageSplatRoute
}

const LangRouteChildren: LangRouteChildren = {
  LangPatRoute: LangPatRoute,
  LangIndexRoute: LangIndexRoute,
  LangWikiSearchRoute: LangWikiSearchRoute,
  LangGraphIndexRoute: LangGraphIndexRoute,
  LangWikiIndexRoute: LangWikiIndexRoute,
  LangGraphNodeSplatRoute: LangGraphNodeSplatRoute,
  LangWikiPageSplatRoute: LangWikiPageSplatRoute,
}

const LangRouteWithChildren = LangRoute._addFileChildren(LangRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LangRoute: LangRouteWithChildren,
  LoginRoute: LoginRoute,
  PatRoute: PatRoute,
  AuthCallbackRoute: AuthCallbackRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
