/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TokenRouteImport } from './routes/token'
import { Route as PatRouteImport } from './routes/pat'
import { Route as LoginRouteImport } from './routes/login'
import { Route as IndexRouteImport } from './routes/index'
import { Route as WikiIndexRouteImport } from './routes/wiki.index'
import { Route as GraphIndexRouteImport } from './routes/graph.index'
import { Route as WikiSearchRouteImport } from './routes/wiki.search'
import { Route as AuthCallbackRouteImport } from './routes/auth.callback'
import { Route as WikiPageSplatRouteImport } from './routes/wiki.page.$'
import { Route as GraphNodeSplatRouteImport } from './routes/graph.node.$'

const TokenRoute = TokenRouteImport.update({
  id: '/token',
  path: '/token',
  getParentRoute: () => rootRouteImport,
} as any)
const PatRoute = PatRouteImport.update({
  id: '/pat',
  path: '/pat',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const WikiIndexRoute = WikiIndexRouteImport.update({
  id: '/wiki/',
  path: '/wiki/',
  getParentRoute: () => rootRouteImport,
} as any)
const GraphIndexRoute = GraphIndexRouteImport.update({
  id: '/graph/',
  path: '/graph/',
  getParentRoute: () => rootRouteImport,
} as any)
const WikiSearchRoute = WikiSearchRouteImport.update({
  id: '/wiki/search',
  path: '/wiki/search',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthCallbackRoute = AuthCallbackRouteImport.update({
  id: '/auth/callback',
  path: '/auth/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const WikiPageSplatRoute = WikiPageSplatRouteImport.update({
  id: '/wiki/page/$',
  path: '/wiki/page/$',
  getParentRoute: () => rootRouteImport,
} as any)
const GraphNodeSplatRoute = GraphNodeSplatRouteImport.update({
  id: '/graph/node/$',
  path: '/graph/node/$',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/pat': typeof PatRoute
  '/token': typeof TokenRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/wiki/search': typeof WikiSearchRoute
  '/graph/': typeof GraphIndexRoute
  '/wiki/': typeof WikiIndexRoute
  '/graph/node/$': typeof GraphNodeSplatRoute
  '/wiki/page/$': typeof WikiPageSplatRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/pat': typeof PatRoute
  '/token': typeof TokenRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/wiki/search': typeof WikiSearchRoute
  '/graph': typeof GraphIndexRoute
  '/wiki': typeof WikiIndexRoute
  '/graph/node/$': typeof GraphNodeSplatRoute
  '/wiki/page/$': typeof WikiPageSplatRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/pat': typeof PatRoute
  '/token': typeof TokenRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/wiki/search': typeof WikiSearchRoute
  '/graph/': typeof GraphIndexRoute
  '/wiki/': typeof WikiIndexRoute
  '/graph/node/$': typeof GraphNodeSplatRoute
  '/wiki/page/$': typeof WikiPageSplatRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/pat'
    | '/token'
    | '/auth/callback'
    | '/wiki/search'
    | '/graph/'
    | '/wiki/'
    | '/graph/node/$'
    | '/wiki/page/$'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/pat'
    | '/token'
    | '/auth/callback'
    | '/wiki/search'
    | '/graph'
    | '/wiki'
    | '/graph/node/$'
    | '/wiki/page/$'
  id:
    | '__root__'
    | '/'
    | '/login'
    | '/pat'
    | '/token'
    | '/auth/callback'
    | '/wiki/search'
    | '/graph/'
    | '/wiki/'
    | '/graph/node/$'
    | '/wiki/page/$'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LoginRoute: typeof LoginRoute
  PatRoute: typeof PatRoute
  TokenRoute: typeof TokenRoute
  AuthCallbackRoute: typeof AuthCallbackRoute
  WikiSearchRoute: typeof WikiSearchRoute
  GraphIndexRoute: typeof GraphIndexRoute
  WikiIndexRoute: typeof WikiIndexRoute
  GraphNodeSplatRoute: typeof GraphNodeSplatRoute
  WikiPageSplatRoute: typeof WikiPageSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/token': {
      id: '/token'
      path: '/token'
      fullPath: '/token'
      preLoaderRoute: typeof TokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pat': {
      id: '/pat'
      path: '/pat'
      fullPath: '/pat'
      preLoaderRoute: typeof PatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/wiki/': {
      id: '/wiki/'
      path: '/wiki'
      fullPath: '/wiki/'
      preLoaderRoute: typeof WikiIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/graph/': {
      id: '/graph/'
      path: '/graph'
      fullPath: '/graph/'
      preLoaderRoute: typeof GraphIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/wiki/search': {
      id: '/wiki/search'
      path: '/wiki/search'
      fullPath: '/wiki/search'
      preLoaderRoute: typeof WikiSearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/callback': {
      id: '/auth/callback'
      path: '/auth/callback'
      fullPath: '/auth/callback'
      preLoaderRoute: typeof AuthCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/wiki/page/$': {
      id: '/wiki/page/$'
      path: '/wiki/page/$'
      fullPath: '/wiki/page/$'
      preLoaderRoute: typeof WikiPageSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/graph/node/$': {
      id: '/graph/node/$'
      path: '/graph/node/$'
      fullPath: '/graph/node/$'
      preLoaderRoute: typeof GraphNodeSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LoginRoute: LoginRoute,
  PatRoute: PatRoute,
  TokenRoute: TokenRoute,
  AuthCallbackRoute: AuthCallbackRoute,
  WikiSearchRoute: WikiSearchRoute,
  GraphIndexRoute: GraphIndexRoute,
  WikiIndexRoute: WikiIndexRoute,
  GraphNodeSplatRoute: GraphNodeSplatRoute,
  WikiPageSplatRoute: WikiPageSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
