/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PatRouteImport } from './routes/pat'
import { Route as LoginRouteImport } from './routes/login'
import { Route as DeviceRouteImport } from './routes/device'
import { Route as LangRouteImport } from './routes/$lang'
import { Route as IndexRouteImport } from './routes/index'
import { Route as LangIndexRouteImport } from './routes/$lang.index'
import { Route as AuthCallbackRouteImport } from './routes/auth.callback'
import { Route as LangPatRouteImport } from './routes/$lang.pat'
import { Route as LangDownloaderRouteImport } from './routes/$lang.downloader'
import { Route as LangDeviceRouteImport } from './routes/$lang.device'
import { Route as LangDashboardRouteImport } from './routes/$lang.dashboard'
import { Route as LangPapersIndexRouteImport } from './routes/$lang.papers.index'
import { Route as LangAdminIndexRouteImport } from './routes/$lang.admin.index'
import { Route as LangPapersSearchRouteImport } from './routes/$lang.papers.search'
import { Route as LangPapersPaperIdRouteImport } from './routes/$lang.papers.$paperId'
import { Route as LangAdminUsersRouteImport } from './routes/$lang.admin.users'
import { Route as LangAdminPluginsRouteImport } from './routes/$lang.admin.plugins'
import { Route as LangAdminPipelinesRouteImport } from './routes/$lang.admin.pipelines'
import { Route as LangAdminDocsRouteImport } from './routes/$lang.admin.docs'
import { Route as LangAdminAssetsRouteImport } from './routes/$lang.admin.assets'
import { Route as LangAdminDbTableRouteImport } from './routes/$lang.admin.db.$table'

const PatRoute = PatRouteImport.update({
  id: '/pat',
  path: '/pat',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const DeviceRoute = DeviceRouteImport.update({
  id: '/device',
  path: '/device',
  getParentRoute: () => rootRouteImport,
} as any)
const LangRoute = LangRouteImport.update({
  id: '/$lang',
  path: '/$lang',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const LangIndexRoute = LangIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LangRoute,
} as any)
const AuthCallbackRoute = AuthCallbackRouteImport.update({
  id: '/auth/callback',
  path: '/auth/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const LangPatRoute = LangPatRouteImport.update({
  id: '/pat',
  path: '/pat',
  getParentRoute: () => LangRoute,
} as any)
const LangDownloaderRoute = LangDownloaderRouteImport.update({
  id: '/downloader',
  path: '/downloader',
  getParentRoute: () => LangRoute,
} as any)
const LangDeviceRoute = LangDeviceRouteImport.update({
  id: '/device',
  path: '/device',
  getParentRoute: () => LangRoute,
} as any)
const LangDashboardRoute = LangDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => LangRoute,
} as any)
const LangPapersIndexRoute = LangPapersIndexRouteImport.update({
  id: '/papers/',
  path: '/papers/',
  getParentRoute: () => LangRoute,
} as any)
const LangAdminIndexRoute = LangAdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => LangRoute,
} as any)
const LangPapersSearchRoute = LangPapersSearchRouteImport.update({
  id: '/papers/search',
  path: '/papers/search',
  getParentRoute: () => LangRoute,
} as any)
const LangPapersPaperIdRoute = LangPapersPaperIdRouteImport.update({
  id: '/papers/$paperId',
  path: '/papers/$paperId',
  getParentRoute: () => LangRoute,
} as any)
const LangAdminUsersRoute = LangAdminUsersRouteImport.update({
  id: '/admin/users',
  path: '/admin/users',
  getParentRoute: () => LangRoute,
} as any)
const LangAdminPluginsRoute = LangAdminPluginsRouteImport.update({
  id: '/admin/plugins',
  path: '/admin/plugins',
  getParentRoute: () => LangRoute,
} as any)
const LangAdminPipelinesRoute = LangAdminPipelinesRouteImport.update({
  id: '/admin/pipelines',
  path: '/admin/pipelines',
  getParentRoute: () => LangRoute,
} as any)
const LangAdminDocsRoute = LangAdminDocsRouteImport.update({
  id: '/admin/docs',
  path: '/admin/docs',
  getParentRoute: () => LangRoute,
} as any)
const LangAdminAssetsRoute = LangAdminAssetsRouteImport.update({
  id: '/admin/assets',
  path: '/admin/assets',
  getParentRoute: () => LangRoute,
} as any)
const LangAdminDbTableRoute = LangAdminDbTableRouteImport.update({
  id: '/admin/db/$table',
  path: '/admin/db/$table',
  getParentRoute: () => LangRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$lang': typeof LangRouteWithChildren
  '/device': typeof DeviceRoute
  '/login': typeof LoginRoute
  '/pat': typeof PatRoute
  '/$lang/dashboard': typeof LangDashboardRoute
  '/$lang/device': typeof LangDeviceRoute
  '/$lang/downloader': typeof LangDownloaderRoute
  '/$lang/pat': typeof LangPatRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/$lang/': typeof LangIndexRoute
  '/$lang/admin/assets': typeof LangAdminAssetsRoute
  '/$lang/admin/docs': typeof LangAdminDocsRoute
  '/$lang/admin/pipelines': typeof LangAdminPipelinesRoute
  '/$lang/admin/plugins': typeof LangAdminPluginsRoute
  '/$lang/admin/users': typeof LangAdminUsersRoute
  '/$lang/papers/$paperId': typeof LangPapersPaperIdRoute
  '/$lang/papers/search': typeof LangPapersSearchRoute
  '/$lang/admin/': typeof LangAdminIndexRoute
  '/$lang/papers/': typeof LangPapersIndexRoute
  '/$lang/admin/db/$table': typeof LangAdminDbTableRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/device': typeof DeviceRoute
  '/login': typeof LoginRoute
  '/pat': typeof PatRoute
  '/$lang/dashboard': typeof LangDashboardRoute
  '/$lang/device': typeof LangDeviceRoute
  '/$lang/downloader': typeof LangDownloaderRoute
  '/$lang/pat': typeof LangPatRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/$lang': typeof LangIndexRoute
  '/$lang/admin/assets': typeof LangAdminAssetsRoute
  '/$lang/admin/docs': typeof LangAdminDocsRoute
  '/$lang/admin/pipelines': typeof LangAdminPipelinesRoute
  '/$lang/admin/plugins': typeof LangAdminPluginsRoute
  '/$lang/admin/users': typeof LangAdminUsersRoute
  '/$lang/papers/$paperId': typeof LangPapersPaperIdRoute
  '/$lang/papers/search': typeof LangPapersSearchRoute
  '/$lang/admin': typeof LangAdminIndexRoute
  '/$lang/papers': typeof LangPapersIndexRoute
  '/$lang/admin/db/$table': typeof LangAdminDbTableRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/$lang': typeof LangRouteWithChildren
  '/device': typeof DeviceRoute
  '/login': typeof LoginRoute
  '/pat': typeof PatRoute
  '/$lang/dashboard': typeof LangDashboardRoute
  '/$lang/device': typeof LangDeviceRoute
  '/$lang/downloader': typeof LangDownloaderRoute
  '/$lang/pat': typeof LangPatRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/$lang/': typeof LangIndexRoute
  '/$lang/admin/assets': typeof LangAdminAssetsRoute
  '/$lang/admin/docs': typeof LangAdminDocsRoute
  '/$lang/admin/pipelines': typeof LangAdminPipelinesRoute
  '/$lang/admin/plugins': typeof LangAdminPluginsRoute
  '/$lang/admin/users': typeof LangAdminUsersRoute
  '/$lang/papers/$paperId': typeof LangPapersPaperIdRoute
  '/$lang/papers/search': typeof LangPapersSearchRoute
  '/$lang/admin/': typeof LangAdminIndexRoute
  '/$lang/papers/': typeof LangPapersIndexRoute
  '/$lang/admin/db/$table': typeof LangAdminDbTableRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$lang'
    | '/device'
    | '/login'
    | '/pat'
    | '/$lang/dashboard'
    | '/$lang/device'
    | '/$lang/downloader'
    | '/$lang/pat'
    | '/auth/callback'
    | '/$lang/'
    | '/$lang/admin/assets'
    | '/$lang/admin/docs'
    | '/$lang/admin/pipelines'
    | '/$lang/admin/plugins'
    | '/$lang/admin/users'
    | '/$lang/papers/$paperId'
    | '/$lang/papers/search'
    | '/$lang/admin/'
    | '/$lang/papers/'
    | '/$lang/admin/db/$table'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/device'
    | '/login'
    | '/pat'
    | '/$lang/dashboard'
    | '/$lang/device'
    | '/$lang/downloader'
    | '/$lang/pat'
    | '/auth/callback'
    | '/$lang'
    | '/$lang/admin/assets'
    | '/$lang/admin/docs'
    | '/$lang/admin/pipelines'
    | '/$lang/admin/plugins'
    | '/$lang/admin/users'
    | '/$lang/papers/$paperId'
    | '/$lang/papers/search'
    | '/$lang/admin'
    | '/$lang/papers'
    | '/$lang/admin/db/$table'
  id:
    | '__root__'
    | '/'
    | '/$lang'
    | '/device'
    | '/login'
    | '/pat'
    | '/$lang/dashboard'
    | '/$lang/device'
    | '/$lang/downloader'
    | '/$lang/pat'
    | '/auth/callback'
    | '/$lang/'
    | '/$lang/admin/assets'
    | '/$lang/admin/docs'
    | '/$lang/admin/pipelines'
    | '/$lang/admin/plugins'
    | '/$lang/admin/users'
    | '/$lang/papers/$paperId'
    | '/$lang/papers/search'
    | '/$lang/admin/'
    | '/$lang/papers/'
    | '/$lang/admin/db/$table'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LangRoute: typeof LangRouteWithChildren
  DeviceRoute: typeof DeviceRoute
  LoginRoute: typeof LoginRoute
  PatRoute: typeof PatRoute
  AuthCallbackRoute: typeof AuthCallbackRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/pat': {
      id: '/pat'
      path: '/pat'
      fullPath: '/pat'
      preLoaderRoute: typeof PatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/device': {
      id: '/device'
      path: '/device'
      fullPath: '/device'
      preLoaderRoute: typeof DeviceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$lang': {
      id: '/$lang'
      path: '/$lang'
      fullPath: '/$lang'
      preLoaderRoute: typeof LangRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$lang/': {
      id: '/$lang/'
      path: '/'
      fullPath: '/$lang/'
      preLoaderRoute: typeof LangIndexRouteImport
      parentRoute: typeof LangRoute
    }
    '/auth/callback': {
      id: '/auth/callback'
      path: '/auth/callback'
      fullPath: '/auth/callback'
      preLoaderRoute: typeof AuthCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$lang/pat': {
      id: '/$lang/pat'
      path: '/pat'
      fullPath: '/$lang/pat'
      preLoaderRoute: typeof LangPatRouteImport
      parentRoute: typeof LangRoute
    }
    '/$lang/downloader': {
      id: '/$lang/downloader'
      path: '/downloader'
      fullPath: '/$lang/downloader'
      preLoaderRoute: typeof LangDownloaderRouteImport
      parentRoute: typeof LangRoute
    }
    '/$lang/device': {
      id: '/$lang/device'
      path: '/device'
      fullPath: '/$lang/device'
      preLoaderRoute: typeof LangDeviceRouteImport
      parentRoute: typeof LangRoute
    }
    '/$lang/dashboard': {
      id: '/$lang/dashboard'
      path: '/dashboard'
      fullPath: '/$lang/dashboard'
      preLoaderRoute: typeof LangDashboardRouteImport
      parentRoute: typeof LangRoute
    }
    '/$lang/papers/': {
      id: '/$lang/papers/'
      path: '/papers'
      fullPath: '/$lang/papers/'
      preLoaderRoute: typeof LangPapersIndexRouteImport
      parentRoute: typeof LangRoute
    }
    '/$lang/admin/': {
      id: '/$lang/admin/'
      path: '/admin'
      fullPath: '/$lang/admin/'
      preLoaderRoute: typeof LangAdminIndexRouteImport
      parentRoute: typeof LangRoute
    }
    '/$lang/papers/search': {
      id: '/$lang/papers/search'
      path: '/papers/search'
      fullPath: '/$lang/papers/search'
      preLoaderRoute: typeof LangPapersSearchRouteImport
      parentRoute: typeof LangRoute
    }
    '/$lang/papers/$paperId': {
      id: '/$lang/papers/$paperId'
      path: '/papers/$paperId'
      fullPath: '/$lang/papers/$paperId'
      preLoaderRoute: typeof LangPapersPaperIdRouteImport
      parentRoute: typeof LangRoute
    }
    '/$lang/admin/users': {
      id: '/$lang/admin/users'
      path: '/admin/users'
      fullPath: '/$lang/admin/users'
      preLoaderRoute: typeof LangAdminUsersRouteImport
      parentRoute: typeof LangRoute
    }
    '/$lang/admin/plugins': {
      id: '/$lang/admin/plugins'
      path: '/admin/plugins'
      fullPath: '/$lang/admin/plugins'
      preLoaderRoute: typeof LangAdminPluginsRouteImport
      parentRoute: typeof LangRoute
    }
    '/$lang/admin/pipelines': {
      id: '/$lang/admin/pipelines'
      path: '/admin/pipelines'
      fullPath: '/$lang/admin/pipelines'
      preLoaderRoute: typeof LangAdminPipelinesRouteImport
      parentRoute: typeof LangRoute
    }
    '/$lang/admin/docs': {
      id: '/$lang/admin/docs'
      path: '/admin/docs'
      fullPath: '/$lang/admin/docs'
      preLoaderRoute: typeof LangAdminDocsRouteImport
      parentRoute: typeof LangRoute
    }
    '/$lang/admin/assets': {
      id: '/$lang/admin/assets'
      path: '/admin/assets'
      fullPath: '/$lang/admin/assets'
      preLoaderRoute: typeof LangAdminAssetsRouteImport
      parentRoute: typeof LangRoute
    }
    '/$lang/admin/db/$table': {
      id: '/$lang/admin/db/$table'
      path: '/admin/db/$table'
      fullPath: '/$lang/admin/db/$table'
      preLoaderRoute: typeof LangAdminDbTableRouteImport
      parentRoute: typeof LangRoute
    }
  }
}

interface LangRouteChildren {
  LangDashboardRoute: typeof LangDashboardRoute
  LangDeviceRoute: typeof LangDeviceRoute
  LangDownloaderRoute: typeof LangDownloaderRoute
  LangPatRoute: typeof LangPatRoute
  LangIndexRoute: typeof LangIndexRoute
  LangAdminAssetsRoute: typeof LangAdminAssetsRoute
  LangAdminDocsRoute: typeof LangAdminDocsRoute
  LangAdminPipelinesRoute: typeof LangAdminPipelinesRoute
  LangAdminPluginsRoute: typeof LangAdminPluginsRoute
  LangAdminUsersRoute: typeof LangAdminUsersRoute
  LangPapersPaperIdRoute: typeof LangPapersPaperIdRoute
  LangPapersSearchRoute: typeof LangPapersSearchRoute
  LangAdminIndexRoute: typeof LangAdminIndexRoute
  LangPapersIndexRoute: typeof LangPapersIndexRoute
  LangAdminDbTableRoute: typeof LangAdminDbTableRoute
}

const LangRouteChildren: LangRouteChildren = {
  LangDashboardRoute: LangDashboardRoute,
  LangDeviceRoute: LangDeviceRoute,
  LangDownloaderRoute: LangDownloaderRoute,
  LangPatRoute: LangPatRoute,
  LangIndexRoute: LangIndexRoute,
  LangAdminAssetsRoute: LangAdminAssetsRoute,
  LangAdminDocsRoute: LangAdminDocsRoute,
  LangAdminPipelinesRoute: LangAdminPipelinesRoute,
  LangAdminPluginsRoute: LangAdminPluginsRoute,
  LangAdminUsersRoute: LangAdminUsersRoute,
  LangPapersPaperIdRoute: LangPapersPaperIdRoute,
  LangPapersSearchRoute: LangPapersSearchRoute,
  LangAdminIndexRoute: LangAdminIndexRoute,
  LangPapersIndexRoute: LangPapersIndexRoute,
  LangAdminDbTableRoute: LangAdminDbTableRoute,
}

const LangRouteWithChildren = LangRoute._addFileChildren(LangRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LangRoute: LangRouteWithChildren,
  DeviceRoute: DeviceRoute,
  LoginRoute: LoginRoute,
  PatRoute: PatRoute,
  AuthCallbackRoute: AuthCallbackRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
